name: Run FIT Tests
run-name: ${{ github.actor }} Running FIT tests on cbdinoclusters
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
            host: github.com
            private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: setup couchbase jvm client 
        run: |
          git clone git@github.com:couchbase/couchbase-jvm-clients.git
          cd couchbase-jvm-clients
          make
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: setup fit 
        run: |
          # cd ..
          git clone git@github.com:couchbaselabs/transactions-fit-performer.git
          cd transactions-fit-performer
          docker build --no-cache -f test-driver/Dockerfile -t fit/test-driver:latest .
          # mvn clean install -Dmaven.test.skip
          # cp test-driver/FITConfiguration.example.json test-driver/FITConfiguration.json
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: setup jenkins sdk
        run: |
          git clone git@github.com:couchbaselabs/jenkins-sdk.git
          cd jenkins-sdk
          ./gradlew buildPerformer --args="-d ../ -i java-performer -s java-sdk"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: Set and Get values from the FITConfiguration.json
      #   id: configJson
      #   uses: RadovanPelka/github-action-json@main
      #   with:
      #     path: "test-driver/FITConfiguration.json"
      #     replaceWith: |
      #       {
      #         "situational": { "capella" : { "url" : ${{  }} } }
      #         "situational": { "capella" : { "accessKey" : ${{  }} } }
      #         "situational": { "capella" : { "privateKey" : ${{  }} } }
      #         "situational": { "capella" : { "projectId" : ${{  }} } }
      #         "situational": { "capella" : { "tenantId" : ${{  }} } }
      #         "situational": { "capella" : { "username" : ${{  }} } }
      #         "situational": { "capella" : { "password" : ${{  }} } }
      #         "excludeTests": []
      #       }
      - name: Edit values from the FITConfiguration.json
        run: |
          cd transactions-fit-performer/test-driver
          # echo "`jq '.excludeTests=${{ env.EXCLUDETESTS}}' FITConfiguration.example.json`" > FITConfiguration.json
          # echo "`jq '.situational.capella.url=${{ env.URL }}' FITConfiguration.example.json`" > FITConfiguration.json
          echo "`jq '.excludeTests="saurabh"' FITConfiguration.example.json`" > FITConfiguration.json
          echo "`jq '.situational.capella.url="saurabh"' FITConfiguration.json`" > FITConfiguration.json
          cat FITConfiguration.json
